const assert = require('node:assert/strict');
const { ChannelLifecycle, ChannelOwnership, ChannelPurpose, PermissionProfile, createGovernedResource } = require('../../../src/domain/community/channelGovernance');
const { buildPermissionReconciliation, isAutomaticDeleteAllowed } = require('../../../src/domain/community/serverGovernanceExecutionPolicy');
const valorant = createGovernedResource({ key: 'category:game:valorant', displayName: 'VALORANT', type: 'category', purpose: ChannelPurpose.GAME_CENTER, owner: ChannelOwnership.MANAGED_CANONICAL, accessProfile: PermissionProfile.SPECIFIC_GAME, accessRoleKey: 'game:valorant', lifecycle: ChannelLifecycle.PERSISTENT, deletePolicy: 'managed_only' });
const voice = createGovernedResource({ key: 'channel:game:valorant:voice', displayName: 'Voice', type: 'voice', parentKey: valorant.key, purpose: ChannelPurpose.GAME_VOICE_ENTRY, owner: ChannelOwnership.MANAGED_CANONICAL, accessProfile: PermissionProfile.VOICE_ENTRY, accessRoleKey: 'game:valorant', lifecycle: ChannelLifecycle.PERSISTENT, deletePolicy: 'managed_only' });
const specific = buildPermissionReconciliation(valorant);
assert.equal(specific.overwrites.some((item) => item.roleKey === 'everyone' && item.deny.includes('ViewChannel')), true);
assert.equal(specific.overwrites.some((item) => item.roleKey === 'game' && item.allow.includes('ViewChannel')), false);
assert.equal(specific.overwrites.some((item) => item.roleKey === 'game:valorant' && item.allow.includes('ViewChannel')), true);
const voicePlan = buildPermissionReconciliation(voice);
assert.equal(voicePlan.overwrites.find((item) => item.roleKey === 'game:valorant').allow.includes('Connect'), true);
const entry = createGovernedResource({ key: 'category:entry', displayName: 'Entry', type: 'category', purpose: ChannelPurpose.ENTRY, owner: ChannelOwnership.MANAGED_CANONICAL, accessProfile: PermissionProfile.PUBLIC_ENTRY, lifecycle: ChannelLifecycle.PERSISTENT, deletePolicy: 'managed_only' });
assert.equal(buildPermissionReconciliation(entry).overwrites.some((item) => item.roleKey === 'guest' && item.allow.includes('ViewChannel')), true);
const readonly = createGovernedResource({ key: 'channel:games:info', displayName: 'Info', type: 'text', parentKey: 'category:games', purpose: ChannelPurpose.GAME_INFO, owner: ChannelOwnership.MANAGED_CANONICAL, accessProfile: PermissionProfile.READONLY_INFO, lifecycle: ChannelLifecycle.PERSISTENT, deletePolicy: 'managed_only' });
assert.equal(buildPermissionReconciliation(readonly).overwrites.find((item) => item.roleKey === 'member').deny.includes('SendMessages'), true);
const gameReadonly = createGovernedResource({ key: 'channel:games:database', displayName: 'Database', type: 'text', parentKey: 'category:games', purpose: ChannelPurpose.GAME_INFO, owner: ChannelOwnership.MANAGED_CANONICAL, accessProfile: PermissionProfile.GAME_READONLY, lifecycle: ChannelLifecycle.PERSISTENT, deletePolicy: 'managed_only' });
const gameReadonlyPlan = buildPermissionReconciliation(gameReadonly);
assert.equal(gameReadonlyPlan.overwrites.find((item) => item.roleKey === 'game').allow.includes('ViewChannel'), true);
assert.equal(gameReadonlyPlan.overwrites.some((item) => item.roleKey === 'member'), false);
assert.equal(isAutomaticDeleteAllowed({ owner: ChannelOwnership.UNKNOWN }), false);
assert.equal(isAutomaticDeleteAllowed({ owner: ChannelOwnership.MANAGED_RUNTIME, lifecycle: ChannelLifecycle.RUNTIME, purpose: ChannelPurpose.RUNTIME_VOICE }), false);
assert.equal(isAutomaticDeleteAllowed({ owner: ChannelOwnership.MANAGED_CANONICAL, lifecycle: ChannelLifecycle.PERSISTENT, purpose: ChannelPurpose.GAME_INFO }), true);
console.log('Server governance execution policy tests passed.');
