const COMMUNITY_PUBLICATION_PERSISTENCE_ERRORS = Object.freeze({
  INVALID_GUILD_ID: 'COMMUNITY_PUBLICATION_INVALID_GUILD_ID',
  RECORD_NOT_FOUND: 'COMMUNITY_PUBLICATION_RECORD_NOT_FOUND',
  MALFORMED_RECORD: 'COMMUNITY_PUBLICATION_MALFORMED_RECORD',
  READ_FAILED: 'COMMUNITY_PUBLICATION_READ_FAILED',
  WRITE_FAILED: 'COMMUNITY_PUBLICATION_WRITE_FAILED',
  INVALID_OPERATION: 'COMMUNITY_PUBLICATION_INVALID_OPERATION',
  UNSUPPORTED_OPERATION: 'COMMUNITY_PUBLICATION_UNSUPPORTED_OPERATION'
});

module.exports = { COMMUNITY_PUBLICATION_PERSISTENCE_ERRORS };
