const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const source = fs.readFileSync(path.resolve(__dirname, '../../src/systems/communityConcierge.js'), 'utf8');
assert.equal(source.includes('getRetainedMessage'), false);
assert.equal(source.includes('lookupPort.lookup'), false);
assert.equal(source.includes('mutationPort.edit'), false);
assert.equal(source.includes('mutationPort.send'), false);
assert.equal(source.includes('channel.messages.fetch'), true);
console.log('Guide Pair retained-message remains unused by runtime');
