const assert = require('node:assert/strict');
const { execFileSync } = require('node:child_process');
const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..', '..');
const runtime = fs.readFileSync(path.join(root, 'src', 'systems', 'communityConcierge.js'), 'utf8');
const reader = fs.readFileSync(path.join(root, 'src', 'infrastructure', 'community', 'CommunityOnboardingStateReader.js'), 'utf8');
const candidate = fs.readFileSync(path.join(root, 'tests', 'fakes', 'community', 'FakeCommunityOnboardingFilesystemBoundary.js'), 'utf8');
const fixture = JSON.parse(fs.readFileSync(path.join(root, 'tests', 'fixtures', 'community', 'community-filesystem-ownership-cases.json'), 'utf8'));
for (const identifier of ['DATA_DIR', 'ONBOARDING_FILE', 'function ensureFile(', 'function readJson(']) assert.equal(runtime.includes(identifier), true, `Current runtime ownership must retain ${identifier}`);
assert.equal(runtime.includes('function writeJson('), false, 'legacy writeJson helper remains removed');
assert.equal((runtime.match(/createCommunityOnboardingStateReader\(/g) || []).length, 3);
assert.equal((runtime.match(/createCommunityOnboardingJsonReader\(/g) || []).length, 3);
assert.equal(reader.includes('filePath, readJson'), false); assert.equal(reader.includes('onboardingJsonReader.readRoot'), true);
for (const forbidden of ['discord.js', 'saveOnboarding', 'mergeRecord', 'updatedAt', 'communityConcierge']) assert.equal(candidate.includes(forbidden), false, `test-only candidate must not introduce ${forbidden}`);
assert.ok(fixture.length >= 50);
const productionChanges = execFileSync('git', ['diff', '--name-only', 'HEAD', '--', 'src'], { cwd: root, encoding: 'utf8' }).trim().split(/\r?\n/).filter(Boolean);
assert.deepEqual(productionChanges, ['src/infrastructure/community/CommunityOnboardingStateReader.js', 'src/systems/communityConcierge.js']);
console.log('Community filesystem ownership migration preserves the approved atomic source boundary.');
