const assert = require('node:assert/strict');
const { execFileSync } = require('node:child_process');
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..', '..');
const source = fs.readFileSync(path.join(root, 'src', 'infrastructure', 'community', 'CommunityOnboardingJsonReader.js'), 'utf8');
const runtime = fs.readFileSync(path.join(root, 'src', 'systems', 'communityConcierge.js'), 'utf8');
for (const forbidden of ['discord.js', 'application/', 'domain/', 'composition/', 'communityConcierge', 'CommunityOnboardingStateReader', 'mergeRecord', 'updatedAt', 'saveOnboarding']) assert.equal(source.includes(forbidden), false, `Reader must not depend on ${forbidden}`);
assert.equal(source.includes('readRoot('), true); assert.equal(source.includes('writeRoot'), false); assert.equal(source.includes('persist'), false); assert.equal(source.includes('cache'), false); assert.equal(source.includes('memo'), false);
assert.equal((runtime.match(/createCommunityOnboardingJsonReader\(\{ dataDirectory: DATA_DIR, filePath: ONBOARDING_FILE \}\)/g) || []).length, 3, 'runtime constructs one reader per closed flow');
assert.equal(runtime.includes('function readJson('), false); assert.equal(runtime.includes("require('node:fs')"), false); assert.equal((runtime.match(/createCommunityOnboardingStateReader\(\{ filePath: ONBOARDING_FILE, readJson \}\)/g) || []).length, 0);
assert.equal(execFileSync('git', ['diff', '--name-only', 'HEAD', '--', 'src/infrastructure/community/CommunityOnboardingJsonReader.js'], { cwd: root, encoding: 'utf8' }).trim(), '');
console.log('Production onboarding JSON reader is isolated and permits only the approved atomic migration source diff.');
