const assert = require('node:assert/strict');
const { createApprovedGovernancePlan, createApprovedOperation, desiredStateFingerprint, inventoryFingerprint, decisionSetFingerprint, ApprovedOperationType } = require('../../../src/domain/community/serverGovernanceApprovedPlan');
const { createExecuteApprovedGovernancePlanUseCase } = require('../../../src/application/community/executeApprovedGovernancePlanUseCase');
const { requiredConfirmation } = require('../../../src/domain/community/governanceExecutionTransaction');
const { buildFullGuildDesiredState } = require('../../../src/domain/community/serverGovernanceDesiredState');
const { compileApprovedGovernancePlan } = require('../../../src/application/community/serverGovernanceApprovedPlanUseCase');
const { createResourceFingerprint } = require('../../../src/domain/community/serverGovernanceReviewDecisionPolicy');
const { createProductionReviewSnapshot } = require('../../fixtures/community/server-governance-production-review-snapshot');

const desired = { resources: [] }; const decisions = [];
function resource(id, name, type = 'text') { return { id, name, type, parentId: null, owner: 'MANAGED_CANONICAL', lifecycle: 'persistent', purpose: 'general', permissionSummary: [] }; }
function plan(inventory, operations) { return createApprovedGovernancePlan({ guildId: 'guild', compiledAt: '2026-08-29T00:00:00.000Z', compiledBy: 'admin', inventoryFingerprint: inventoryFingerprint(inventory), desiredStateFingerprint: desiredStateFingerprint(desired), decisionSetFingerprint: decisionSetFingerprint(decisions), operations }); }
function store() { const transactions = []; const locks = new Set(); const audit = []; return { transactions, audit, acquireLock: ({ guildId }) => { if (locks.has(guildId)) return false; locks.add(guildId); return true; }, releaseLock: ({ guildId }) => locks.delete(guildId), findSucceededPlan: ({ guildId, planFingerprint }) => transactions.find((item) => item.guildId === guildId && item.planFingerprint === planFingerprint && item.status === 'SUCCEEDED') || null, findActiveTransaction: ({ guildId }) => transactions.find((item) => item.guildId === guildId && ['PENDING', 'VERIFYING', 'LOCKED', 'EXECUTING', 'ROLLING_BACK'].includes(item.status)) || null, createTransaction: ({ transaction }) => transactions.push({ ...transaction }), updateTransaction: ({ transactionId, patch }) => Object.assign(transactions.find((item) => item.transactionId === transactionId), patch), recordAudit: (event) => audit.push(event), recoverInterrupted: ({ guildId }) => { let count = 0; for (const item of transactions) if (item.guildId === guildId && ['PENDING', 'VERIFYING', 'LOCKED', 'EXECUTING', 'ROLLING_BACK'].includes(item.status)) { item.status = 'INTERRUPTED_REQUIRES_REVIEW'; count += 1; } locks.delete(guildId); return count; } }; }
function gateway(initial, { failType = null, rollbackFail = false, driftId = null, externalCreateChange = false } = {}) { const resources = new Map(initial.map((item) => [item.id, { ...item }])); const calls = []; let reads = 0; const readsByResource = new Map(); return { calls, async readInventory() { return [...resources.values()].map((item) => ({ ...item })); }, async readResourceState({ resourceId }) { reads += 1; readsByResource.set(resourceId, (readsByResource.get(resourceId) || 0) + 1); const value = resources.get(resourceId); if (driftId === resourceId && reads > 1) value.name = 'external-drift'; if (externalCreateChange && resourceId.startsWith('created-') && readsByResource.get(resourceId) > 1) value.name = 'external-change'; return value ? { ...value } : null; }, async createCategory({ operation }) { calls.push('CREATE_CATEGORY'); const id = `created-${operation.operationId}`; resources.set(id, resource(id, operation.expectedSnapshot.name, 'category')); return { resourceId: id }; }, async createChannel({ operation }) { calls.push('CREATE_CHANNEL'); const id = `created-${operation.operationId}`; resources.set(id, resource(id, operation.expectedSnapshot.name, operation.expectedSnapshot.type)); return { resourceId: id }; }, async moveResource({ resourceId }) { calls.push('MOVE_RESOURCE'); if (failType === 'MOVE_RESOURCE') throw new Error('injected'); return { resourceId }; }, async renameResource({ resourceId, operation }) { calls.push('RENAME_RESOURCE'); if (failType === 'RENAME_RESOURCE') throw new Error('injected'); resources.get(resourceId).name = operation.expectedSnapshot.name; return { resourceId }; }, async updatePermissions({ resourceId }) { calls.push('UPDATE_PERMISSIONS'); if (failType === 'UPDATE_PERMISSIONS') throw new Error('injected'); return { resourceId }; }, async deleteChannel({ resourceId }) { calls.push('DELETE_CHANNEL'); if (failType === 'DELETE_CHANNEL' || (rollbackFail && resourceId.startsWith('created-'))) throw new Error('injected'); resources.delete(resourceId); }, async deleteCategory({ resourceId }) { calls.push('DELETE_CATEGORY'); resources.delete(resourceId); } }; }
function operation(operationId, type, currentSnapshot = null, expectedSnapshot = null, dependencies = []) { return createApprovedOperation({ operationId, type, resourceId: currentSnapshot?.id || null, canonicalTargetKey: expectedSnapshot?.canonicalKey || operationId, currentSnapshot, expectedSnapshot, reason: 'test', dependencies, permission: type === ApprovedOperationType.UPDATE_PERMISSIONS ? { overwrites: [] } : null }); }
async function execute(gatewayInstance, txStore, approvedPlan, overrides = {}) { return createExecuteApprovedGovernancePlanUseCase({ transactionStore: txStore, mutationGateway: gatewayInstance, executionEnabled: true }).execute({ guildId: 'guild', actorId: 'admin', planRecord: { plan: approvedPlan, storageStatus: 'ACTIVE' }, confirmation: requiredConfirmation(approvedPlan.planFingerprint), freshDesiredState: desired, freshDecisions: decisions, ...overrides }); }

void (async () => {
  const old = resource('old', 'Old'); const doomed = resource('doomed', 'Doomed'); const created = { name: 'Created', type: 'text', canonicalKey: 'channel:created' }; const renamed = { ...old, name: 'Renamed' };
  const operations = [operation('01-create', ApprovedOperationType.CREATE_CHANNEL, null, created), operation('02-rename', ApprovedOperationType.RENAME_RESOURCE, old, renamed), operation('03-permission', ApprovedOperationType.UPDATE_PERMISSIONS, old, renamed), operation('04-delete', ApprovedOperationType.DELETE_CHANNEL, doomed, null)];
  const approved = plan([old, doomed], operations); const happyStore = store(); const happyGateway = gateway([old, doomed]); const happy = await execute(happyGateway, happyStore, approved);
  assert.equal(happy.status, 'SUCCEEDED'); assert.equal(happy.operationResults.length, 4); assert.equal(happy.rollbackResults.length, 0); assert.deepEqual(happyGateway.calls, ['CREATE_CHANNEL', 'RENAME_RESOURCE', 'UPDATE_PERMISSIONS', 'DELETE_CHANNEL']); assert.equal(happyGateway.calls.filter((item) => item === 'DELETE_CHANNEL').length, 1);
  const duplicate = await execute(happyGateway, happyStore, approved); assert.equal(duplicate.finalVerification.code, 'PLAN_ALREADY_EXECUTED'); assert.equal(happyGateway.calls.length, 4);
  const earlyStore = store(); const earlyGateway = gateway([old, doomed], { failType: 'RENAME_RESOURCE' }); const early = await execute(earlyGateway, earlyStore, approved); assert.equal(early.status, 'ROLLED_BACK'); assert.equal(early.rollbackResults[0].state, 'ROLLED_BACK'); assert.equal(early.operationResults.some((item) => item.operationId === '04-delete' && item.state === 'SUCCEEDED'), false);
  const driftStore = store(); const driftGateway = gateway([old, doomed], { driftId: 'old' }); const drift = await execute(driftGateway, driftStore, approved); assert.equal(drift.finalVerification.code, 'RESOURCE_PRECONDITION_FAILED'); assert.equal(drift.operationResults.some((item) => item.operationId === '04-delete' && item.state === 'SUCCEEDED'), false);
  const externalStore = store(); const externalGateway = gateway([old, doomed], { failType: 'RENAME_RESOURCE', externalCreateChange: true }); const external = await execute(externalGateway, externalStore, approved); assert.equal(external.status, 'PARTIAL_ROLLBACK'); assert.equal(external.rollbackResults[0].state, 'ROLLBACK_FAILED');
  const afterDeletePlan = plan([old, doomed], [operation('01-delete', ApprovedOperationType.DELETE_CHANNEL, doomed, null), operation('02-permission', ApprovedOperationType.UPDATE_PERMISSIONS, old, old)]); const afterDelete = await execute(gateway([old, doomed], { failType: 'UPDATE_PERMISSIONS' }), store(), afterDeletePlan); assert.equal(afterDelete.status, 'PARTIAL_ROLLBACK'); assert.equal(afterDelete.irreversibleOperationsCompleted.includes('01-delete'), true);
  const wrongStore = store(); const wrongGateway = gateway([old, doomed]); const wrong = await execute(wrongGateway, wrongStore, approved, { confirmation: 'EXECUTE_wrong' }); assert.equal(wrong.finalVerification.code, 'CONFIRMATION_MISMATCH'); assert.equal(wrongGateway.calls.length, 0);
  const superseded = await execute(gateway([old, doomed]), store(), approved, { planRecord: { plan: approved, storageStatus: 'SUPERSEDED' } }); assert.equal(superseded.finalVerification.code, 'PLAN_SUPERSEDED');
  const interruptedStore = store(); interruptedStore.createTransaction({ transaction: { transactionId: 'old', guildId: 'guild', status: 'EXECUTING' } }); const useCase = createExecuteApprovedGovernancePlanUseCase({ transactionStore: interruptedStore, mutationGateway: gateway([old, doomed]), executionEnabled: true }); assert.equal(useCase.recoverInterrupted({ guildId: 'guild' }), 1); assert.equal(interruptedStore.transactions[0].status, 'INTERRUPTED_REQUIRES_REVIEW');
  const productionDesired = buildFullGuildDesiredState(); const productionSnapshot = createProductionReviewSnapshot(productionDesired);
  const productionDecisions = productionSnapshot.inventory.filter((item) => item.id.startsWith('custom-') || item.migrationReviewReason).map((item) => ({ guildId: 'production', resourceId: item.id, resourceFingerprint: createResourceFingerprint(item), decision: item.id.startsWith('custom-') ? 'IGNORE_GOVERNANCE' : item.migrationReviewReason.includes('voice_only') ? 'DELETE' : 'KEEP', canonicalTargetKey: null, schemaVersion: 1 }));
  const productionPlan = compileApprovedGovernancePlan({ guildId: 'production', compiledBy: 'admin', inventory: productionSnapshot.inventory, desiredState: productionDesired, decisions: productionDecisions, compiledAt: '2026-08-29T00:00:00.000Z' }); const productionGateway = gateway(productionSnapshot.inventory); const productionStore = store();
  const productionReceipt = await createExecuteApprovedGovernancePlanUseCase({ transactionStore: productionStore, mutationGateway: productionGateway, executionEnabled: true }).execute({ guildId: 'production', actorId: 'admin', planRecord: { plan: productionPlan, storageStatus: 'ACTIVE' }, confirmation: requiredConfirmation(productionPlan.planFingerprint), freshDesiredState: productionDesired, freshDecisions: productionDecisions });
  assert.equal(productionPlan.operations.length, 24); assert.equal(productionReceipt.status, 'SUCCEEDED'); assert.equal(productionReceipt.operationResults.length, 24);
  console.log('Server governance execution safety tests passed.');
})();
