const assert = require('node:assert/strict');
const GAME_REGISTRY = require('../../../src/domain/games/gameRegistry');
const { buildFullGuildDesiredState } = require('../../../src/domain/community/serverGovernanceDesiredState');
const { GovernanceAction } = require('../../../src/domain/community/channelGovernance');
const { buildGovernancePermissionMatrix, validateProjectedGuildQuality } = require('../../../src/domain/community/serverGovernanceReleaseCandidate');
const { createServerGovernancePlan, buildFullGuildGovernancePreview } = require('../../../src/application/community/createServerGovernancePlanUseCase');
const { createServerGovernanceExecutionUseCase } = require('../../../src/application/community/serverGovernanceExecutionUseCase');
const { ExecutionMode } = require('../../../src/domain/community/serverGovernanceExecutionPolicy');
const { roleCanAccessGame, roleCanAccessGameCenter } = require('../../../src/domain/games/gameAccessPolicy');
const { createProductionShapedGuildInventory } = require('../../fixtures/community/server-governance-production-shaped-guild');

const desiredState = buildFullGuildDesiredState();
const inventory = createProductionShapedGuildInventory(desiredState);
const plan = createServerGovernancePlan({ inventory, desiredState });
const preview = buildFullGuildGovernancePreview({ inventory, desiredState });
const matrix = buildGovernancePermissionMatrix(desiredState, GAME_REGISTRY);
const quality = validateProjectedGuildQuality({ desiredState, gameRegistry: GAME_REGISTRY, plan });
assert.equal(preview.summary.review >= 1, true);
assert.equal(preview.summary.protected >= 2, true);
assert.equal(quality.ok, true);
assert.equal(matrix.everyone['category:admin'], false);
assert.equal(matrix.member['category:game:valorant'], false);
assert.equal(matrix.game['category:game:valorant'], false);
assert.equal(matrix['game:valorant']['category:game:valorant'], true);
assert.equal(matrix['game:valorant']['category:game:apex'], false);
assert.equal(matrix.dev['channel:dev'], true);
assert.equal(matrix.invest['channel:invest'], true);
assert.equal(roleCanAccessGameCenter(['member', 'game']), true);
assert.equal(roleCanAccessGame(['member', 'game:valorant'], 'valorant'), true);
assert.equal(roleCanAccessGame(['member', 'game:valorant'], 'apex'), false);
assert.equal(matrix['game:valorant']['channel:game:valorant:voice_entry'], true);
const writes = [];
const rolesByKey = Object.fromEntries(['guest', 'member', 'game', 'dev', 'invest', 'creator', 'night', 'owner', 'admin', 'mod', ...GAME_REGISTRY.map((game) => `game:${game.id}`)].map((key) => [key, key]));
const gateway = { readExecutionSnapshot: async () => ({ guildExists: true, permissions: { ManageChannels: true, ManageRoles: true, ViewChannel: true }, rolesByKey, inventory }), createCategory: async () => writes.push('createCategory'), createTextChannel: async () => writes.push('createTextChannel'), createVoiceChannel: async () => writes.push('createVoiceChannel'), moveChannel: async () => writes.push('move'), renameChannel: async () => writes.push('rename'), applyCategoryPermissions: async () => writes.push('categoryPermission'), applyChannelPermissions: async () => writes.push('channelPermission'), deleteChannel: async () => writes.push('deleteChannel'), deleteCategory: async () => writes.push('deleteCategory') };
const approvedPlan = { actions: plan.actions.filter((action) => ![GovernanceAction.REVIEW, GovernanceAction.REVIEW_DELETE, GovernanceAction.CONFLICT].includes(action.action)) };
void (async () => {
  const execution = await createServerGovernanceExecutionUseCase({ mutationGateway: gateway, desiredState }).execute({ guildId: 'fixture-guild', plan: approvedPlan, inventory, mode: ExecutionMode.DRY_RUN });
  assert.equal(execution.preflight.ok, true);
  assert.equal(writes.length, 0);
  assert.equal(execution.results.some((result) => result.type === GovernanceAction.SAFE_DELETE), true);
  assert.equal(plan.actions.filter((action) => action.action === GovernanceAction.SAFE_DELETE).every((action) => action.reason), true);
  assert.equal(plan.actions.filter((action) => action.action === GovernanceAction.SAFE_DELETE).some((action) => ['runtime-voice', 'ticket-1'].includes(action.resourceId)), false);
  console.log('Server governance release-candidate integration tests passed.');
})();
